blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/YOURNAME/REPO-NAME/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/YOURNAME/REPO-NAME/wiki
    about: Please check our documentation first.